#if !canImport(ObjectiveC)
import XCTest

extension SQLiteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQLiteTests = [
        ("testBenchmark", testBenchmark),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SQLiteTests.__allTests__SQLiteTests),
    ]
}
#endif
