#ifndef SQLITE_VAPOR_CONFIG_H__
#define SQLITE_VAPOR_CONFIG_H__

#ifndef SQLITE_DEFAULT_CACHE_SIZE
#define SQLITE_DEFAULT_CACHE_SIZE 2000
#endif

#ifndef SQLITE_DEFAULT_CKPTFULLFSYNC
#define SQLITE_DEFAULT_CKPTFULLFSYNC 1
#endif

#ifndef SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT
#define SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT 32768
#endif

#ifndef SQLITE_DEFAULT_PAGE_SIZE
#define SQLITE_DEFAULT_PAGE_SIZE 4096
#endif

#ifndef SQLITE_DEFAULT_SYNCHRONOUS
#define SQLITE_DEFAULT_SYNCHRONOUS 2
#endif

#ifndef SQLITE_DEFAULT_WAL_SYNCHRONOUS
#define SQLITE_DEFAULT_WAL_SYNCHRONOUS 1
#endif

#ifndef SQLITE_ENABLE_API_ARMOR
#define SQLITE_ENABLE_API_ARMOR 1
#endif

#ifndef SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_ENABLE_COLUMN_METADATA 1
#endif

#ifndef SQLITE_ENABLE_DBSTAT_VTAB
#define SQLITE_ENABLE_DBSTAT_VTAB 1
#endif

#ifndef SQLITE_ENABLE_FTS3
#define SQLITE_ENABLE_FTS3 1
#endif

#ifndef SQLITE_ENABLE_FTS3_PARENTHESIS
#define SQLITE_ENABLE_FTS3_PARENTHESIS 1
#endif

#ifndef SQLITE_ENABLE_FTS3_TOKENIZER
#define SQLITE_ENABLE_FTS3_TOKENIZER 1
#endif

#ifndef SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS4 1
#endif

#ifndef SQLITE_ENABLE_FTS5
#define SQLITE_ENABLE_FTS5 1
#endif

#ifndef SQLITE_ENABLE_JSON1
#define SQLITE_ENABLE_JSON1 1
#endif

#ifndef SQLITE_ENABLE_PREUPDATE_HOOK
#define SQLITE_ENABLE_PREUPDATE_HOOK 1
#endif

#ifndef SQLITE_ENABLE_RTREE
#define SQLITE_ENABLE_RTREE 1
#endif

#ifndef SQLITE_ENABLE_SESSION
#define SQLITE_ENABLE_SESSION 1
#endif

#ifndef SQLITE_ENABLE_SNAPSHOT
#define SQLITE_ENABLE_SNAPSHOT 1
#endif

#ifndef SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION
#define SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION 1
#endif

#ifndef SQLITE_ENABLE_UPDATE_DELETE_LIMIT
#define SQLITE_ENABLE_UPDATE_DELETE_LIMIT 1
#endif

#ifndef SQLITE_HAS_CODEC_RESTRICTED
#define SQLITE_HAS_CODEC_RESTRICTED 1
#endif

#ifndef SQLITE_HAVE_ISNAN
#define SQLITE_HAVE_ISNAN 1
#endif

#ifndef SQLITE_MAX_LENGTH
#define SQLITE_MAX_LENGTH 2147483645
#endif

#ifndef SQLITE_MAX_MMAP_SIZE
#define SQLITE_MAX_MMAP_SIZE 1073741824
#endif

#ifndef SQLITE_MAX_VARIABLE_NUMBER
#define SQLITE_MAX_VARIABLE_NUMBER 500000
#endif

#ifndef SQLITE_OMIT_AUTORESET
#define SQLITE_OMIT_AUTORESET 1
#endif

#ifndef SQLITE_OMIT_LOAD_EXTENSION
#define SQLITE_OMIT_LOAD_EXTENSION 1
#endif

#ifndef SQLITE_STMTJRNL_SPILL
#define SQLITE_STMTJRNL_SPILL 131072
#endif

#ifndef SQLITE_THREADSAFE
#define SQLITE_THREADSAFE 2
#endif

#ifndef SQLITE_USE_URI
#define SQLITE_USE_URI 1
#endif

#endif // SQLITE_VAPOR_CONFIG_H__